#!/usr/bin/env bash
# Bintra per-customer OpenClaw installer.
# Run on a fresh Ubuntu 24.04 droplet as root (or with sudo).
#
# Required env vars before running:
#   CUSTOMER_ID              — UUID from the Bintra portal users table
#   CUSTOMER_LLM_PROVIDER    — openai | anthropic | gemini
#   CUSTOMER_LLM_MODEL       — e.g. claude-opus-4-6, gpt-5.4, gemini-3.1-pro-preview
#   CUSTOMER_LLM_KEY         — decrypted API key from the portal
#   CUSTOMER_BOT_TOKEN       — Telegram bot token from @BotFather (one bot per customer)
#   CUSTOMER_WEBHOOK_SECRET  — per-customer shared secret the Manager uses to sign
#                              HMAC-SHA256 events it POSTs to the Bintra portal at
#                              /api/droplet/report. Generated by the Bintra provisioner.
#
# Optional:
#   CONFIG_REPO_URL          — git URL for this repo (defaults to https://github.com/bintra/openclaw-config.git)

set -euo pipefail

: "${CUSTOMER_ID:?CUSTOMER_ID not set}"
: "${CUSTOMER_LLM_PROVIDER:?CUSTOMER_LLM_PROVIDER not set}"
: "${CUSTOMER_LLM_MODEL:?CUSTOMER_LLM_MODEL not set}"
: "${CUSTOMER_LLM_KEY:?CUSTOMER_LLM_KEY not set}"
: "${CUSTOMER_BOT_TOKEN:?CUSTOMER_BOT_TOKEN not set}"
: "${CUSTOMER_WEBHOOK_SECRET:?CUSTOMER_WEBHOOK_SECRET not set}"

CONFIG_REPO_URL="${CONFIG_REPO_URL:-https://github.com/redomen2828/bintra-openclaw-config.git}"
INSTALL_ROOT="/opt/bintra"
CONFIG_DIR="$HOME/.openclaw"
SERVICE_FILE="/etc/systemd/system/openclaw.service"

# --- Customer-change state wipe --------------------------------------------
# If the droplet was previously provisioned for a different CUSTOMER_ID,
# the existing workspace/session state belongs to that prior customer. We
# MUST NOT let it bleed into the new customer's environment (MEMORY.md,
# USER.md, IDENTITY.md, memory/ daily logs, knowledge/, sessions). Detect
# and wipe.
#
# Same-customer re-install (config bump, version upgrade) should preserve
# state so conversation history and the Manager's memory stay intact.
#
# Caller can force a wipe with FORCE_WIPE=1 (used by scripts/reset-droplet.ts).
PREV_CUSTOMER_ID=""
if [ -f "$SERVICE_FILE" ]; then
  PREV_CUSTOMER_ID="$(awk -F= '/^Environment=CUSTOMER_ID=/ { print $3; exit }' "$SERVICE_FILE" || true)"
fi

WIPE_STATE=0
WIPE_REASON=""
if [ "${FORCE_WIPE:-0}" = "1" ]; then
  WIPE_STATE=1
  WIPE_REASON="FORCE_WIPE=1"
elif [ -n "$PREV_CUSTOMER_ID" ] && [ "$PREV_CUSTOMER_ID" != "$CUSTOMER_ID" ]; then
  WIPE_STATE=1
  WIPE_REASON="droplet was provisioned for $PREV_CUSTOMER_ID; now reprovisioning for $CUSTOMER_ID"
fi

if [ "$WIPE_STATE" = "1" ]; then
  echo "==> Customer-change state wipe ($WIPE_REASON)"
  systemctl stop openclaw.service 2>/dev/null || true
  # Also stop/disable the credit-balance watcher — it holds the prior
  # customer's CUSTOMER_BOT_TOKEN in its unit env, and we don't want it
  # tailing logs across the customer transition. We re-enable it at the
  # end of this script with fresh env values.
  systemctl stop bintra-credit-watcher.service 2>/dev/null || true
  systemctl disable bintra-credit-watcher.service 2>/dev/null || true
  rm -f "$INSTALL_ROOT/workspace/MEMORY.md" \
        "$INSTALL_ROOT/workspace/IDENTITY.md" \
        "$INSTALL_ROOT/workspace/USER.md" \
        "$INSTALL_ROOT/workspace/BOOTSTRAP.md" \
        "$INSTALL_ROOT/workspace/HEARTBEAT.md" \
        "$INSTALL_ROOT/workspace/TOOLS.md"
  rm -rf "$INSTALL_ROOT/workspace/memory" \
         "$INSTALL_ROOT/workspace/knowledge" \
         "$INSTALL_ROOT/workspace/customer_notes" \
         "$INSTALL_ROOT/workspace/state"
  rm -f "$INSTALL_ROOT/sessions/sessions.json"
  rm -rf "$CONFIG_DIR/agents"
  echo "   state wiped"
fi
# --- end wipe ---------------------------------------------------------------

echo "==> System packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git ca-certificates jq

echo "==> Swap (prevents OOM during npm install on 2GB droplets)"
if ! swapon --show | grep -q '/swapfile'; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  if ! grep -q '/swapfile' /etc/fstab; then
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
  fi
fi

echo "==> Node.js 24 LTS"
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
  apt-get install -y nodejs
fi

echo "==> OpenClaw"
npm install -g openclaw@latest

echo "==> Workspace at $INSTALL_ROOT"
mkdir -p "$INSTALL_ROOT" "$INSTALL_ROOT/sessions" "$INSTALL_ROOT/workspace" "$INSTALL_ROOT/workspace/customer_notes" "/data/research"
# Symlink research into the workspace so the Manager can read it. OpenClaw's
# "coding" tool profile restricts filesystem access to the workspace root; the
# research drop target lives at /data/research/ for backup convenience, so
# surface it under workspace/research/ via symlink.
ln -sfn /data/research "$INSTALL_ROOT/workspace/research"
if [ ! -d "$INSTALL_ROOT/.config-repo/.git" ]; then
  git clone "$CONFIG_REPO_URL" "$INSTALL_ROOT/.config-repo"
else
  git -C "$INSTALL_ROOT/.config-repo" fetch --all --quiet
  git -C "$INSTALL_ROOT/.config-repo" reset --hard origin/main --quiet
fi

echo "==> Bintra patches on openclaw"
# Must run AFTER the openclaw install and AFTER the config-repo clone (patch
# source lives in the repo). npm install overwrites the package on every run,
# so we reapply every time. Idempotent; the patch script fails loudly if the
# upstream bundle layout shifts so we know to rebase.
if [ -f "$INSTALL_ROOT/.config-repo/patches/patch-openclaw-final-tag.js" ]; then
  node "$INSTALL_ROOT/.config-repo/patches/patch-openclaw-final-tag.js"
fi
if [ -f "$INSTALL_ROOT/.config-repo/patches/patch-openclaw-tool-error-warning.js" ]; then
  node "$INSTALL_ROOT/.config-repo/patches/patch-openclaw-tool-error-warning.js"
fi

# Copy workspace: refresh everything EXCEPT customer-state files (MEMORY.md,
# IDENTITY.md, USER.md) that the Manager owns and mutates across sessions. If
# we clobbered those on a same-customer re-install (config bump / version
# upgrade), we'd wipe the Manager's accumulated memory of the customer. The
# customer-change wipe above already nukes them when CUSTOMER_ID changes.
rsync -a \
      --exclude 'MEMORY.md' \
      --exclude 'IDENTITY.md' \
      --exclude 'USER.md' \
      "$INSTALL_ROOT/.config-repo/workspace/" "$INSTALL_ROOT/workspace/"
# Seed the state files only if missing (fresh customer → use repo template;
# existing customer → preserve Manager's state).
for f in MEMORY.md IDENTITY.md USER.md; do
  if [ ! -f "$INSTALL_ROOT/workspace/$f" ] && [ -f "$INSTALL_ROOT/.config-repo/workspace/$f" ]; then
    cp "$INSTALL_ROOT/.config-repo/workspace/$f" "$INSTALL_ROOT/workspace/$f"
  fi
done
# Ensure agent-writable subdirs exist (safe if already present).
# workspace/state is the rendezvous point for out-of-band watchers:
# capture-chat-id hook writes primary-chat-id here; credit-balance
# watcher reads it. Must exist before the Manager takes its first
# inbound, which is why we mkdir it now rather than letting the hook
# create it lazily.
mkdir -p "$INSTALL_ROOT/workspace/memory" "$INSTALL_ROOT/workspace/knowledge" "$INSTALL_ROOT/workspace/state"
# convothathappened.txt is a dev artifact from the config repo — never ship to customers
rm -f "$INSTALL_ROOT/workspace/convothathappened.txt"

# Substitute {{CUSTOMER_ID}} placeholders in workspace markdown files. Skill
# files (e.g. check_research_results/SKILL.md) reference paths like
# /data/research/{{CUSTOMER_ID}}.json — the Manager reads these literally, so
# the token must be rendered at provision time. Runs against all AGENTS.md and
# skills/*/SKILL.md files under workspace/.
find "$INSTALL_ROOT/workspace" -type f \( -name 'AGENTS.md' -o -name 'SKILL.md' -o -name 'SOUL.md' \) \
  -exec sed -i "s|{{CUSTOMER_ID}}|$CUSTOMER_ID|g" {} +
cp "$INSTALL_ROOT/.config-repo/openclaw.json.template" "$INSTALL_ROOT/openclaw.json.template"
cp "$INSTALL_ROOT/.config-repo/research_results.template.json" "$INSTALL_ROOT/research_results.template.json"

echo "==> bintra-report helper (one-command wrapper for /api/droplet/report)"
install -m 0755 "$INSTALL_ROOT/.config-repo/bintra-report.sh" /usr/local/bin/bintra-report

echo "==> Rendering openclaw.json"
mkdir -p "$CONFIG_DIR"

# OpenClaw's model prefix differs from our internal provider enum:
#   portal enum  -> openclaw prefix
#   openai       -> openai
#   anthropic    -> anthropic
#   gemini       -> google
case "$CUSTOMER_LLM_PROVIDER" in
  openai)    OPENCLAW_PREFIX="openai" ;;
  anthropic) OPENCLAW_PREFIX="anthropic" ;;
  gemini)    OPENCLAW_PREFIX="google" ;;
  *) echo "Unknown provider: $CUSTOMER_LLM_PROVIDER" >&2; exit 1 ;;
esac
CUSTOMER_LLM_MODEL_FQN="$OPENCLAW_PREFIX/$CUSTOMER_LLM_MODEL"

sed \
  -e "s|{{CUSTOMER_ID}}|$CUSTOMER_ID|g" \
  -e "s|{{CUSTOMER_BOT_TOKEN}}|$CUSTOMER_BOT_TOKEN|g" \
  -e "s|{{CUSTOMER_LLM_PROVIDER}}|$CUSTOMER_LLM_PROVIDER|g" \
  -e "s|{{CUSTOMER_LLM_MODEL}}|$CUSTOMER_LLM_MODEL|g" \
  -e "s|{{CUSTOMER_LLM_MODEL_FQN}}|$CUSTOMER_LLM_MODEL_FQN|g" \
  "$INSTALL_ROOT/openclaw.json.template" > "$CONFIG_DIR/openclaw.json"

echo "==> Provider API key via auth-profiles.json"
# We write every env-var alias each provider might read under, so OpenClaw
# version bumps (which sometimes change the lookup name, e.g.
# GOOGLE_API_KEY vs GOOGLE_GENERATIVE_AI_API_KEY) don't silently break auth.
case "$CUSTOMER_LLM_PROVIDER" in
  openai)
    ENV_KEYS=(OPENAI_API_KEY)
    ;;
  anthropic)
    ENV_KEYS=(ANTHROPIC_API_KEY)
    ;;
  gemini)
    ENV_KEYS=(GOOGLE_API_KEY GOOGLE_GENERATIVE_AI_API_KEY GEMINI_API_KEY)
    ;;
  *) echo "Unknown provider: $CUSTOMER_LLM_PROVIDER" >&2; exit 1 ;;
esac

# Build the JSON env map for auth-profiles.json
ENV_JSON_ENTRIES=""
for k in "${ENV_KEYS[@]}"; do
  if [ -n "$ENV_JSON_ENTRIES" ]; then
    ENV_JSON_ENTRIES="$ENV_JSON_ENTRIES,"$'\n'
  fi
  ENV_JSON_ENTRIES="$ENV_JSON_ENTRIES    \"$k\": \"$CUSTOMER_LLM_KEY\""
done

cat > "$CONFIG_DIR/auth-profiles.json" <<EOF
{
  "env": {
$ENV_JSON_ENTRIES
  }
}
EOF
chmod 600 "$CONFIG_DIR/auth-profiles.json"

# HARDENING 2.2: write the LLM key to a mode-0600 EnvironmentFile instead of
# embedding it inline in the systemd unit. journalctl / systemctl show can
# leak inline Environment= values to non-root contexts under some configs;
# EnvironmentFile is only readable by root.
AUTH_ENV_FILE="$CONFIG_DIR/auth.env"
: > "$AUTH_ENV_FILE"
chmod 600 "$AUTH_ENV_FILE"
for k in "${ENV_KEYS[@]}"; do
  echo "$k=$CUSTOMER_LLM_KEY" >> "$AUTH_ENV_FILE"
done

# Primary key (first in the list) — used for the systemd unit below so logs
# stay readable. All aliases are in auth-profiles.json.
ENV_KEY="${ENV_KEYS[0]}"

echo "==> openclaw doctor --fix (auto-migrate + generate gateway token)"
openclaw doctor --fix </dev/null || true

# `openclaw doctor --fix` plants a competing user-level systemd unit at
# /root/.config/systemd/user/openclaw-gateway.service. It fights our
# system-level openclaw.service for 127.0.0.1:18789; both crashloop
# until one of them wins. Kill the user-level copy on every install.
# Observed 2026-04-20: this caused ~4min of first-message silence on
# Peter's droplet. See HARDENING.md 1.10.
echo "==> removing stray user-level openclaw-gateway unit (doctor --fix side effect)"
systemctl --user stop openclaw-gateway.service 2>/dev/null || true
systemctl --user disable openclaw-gateway.service 2>/dev/null || true
rm -f /root/.config/systemd/user/openclaw-gateway.service
rm -f /root/.config/systemd/user/default.target.wants/openclaw-gateway.service
# Belt-and-suspenders: root should never have user-level services at boot.
loginctl disable-linger root 2>/dev/null || true

echo "==> systemd service"
# ExecStartPre/Post/StopPost emit gateway_phase events so the admin panel can
# see phase transitions in real time without waiting for the next heartbeat.
# All three calls are fire-and-forget (trailing `|| true`) — a webhook failure
# must never block the gateway from starting or restarting.
cat > /etc/systemd/system/openclaw.service <<EOF
[Unit]
Description=OpenClaw gateway for Bintra customer $CUSTOMER_ID
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$AUTH_ENV_FILE
Environment=HOME=$HOME
Environment=CUSTOMER_ID=$CUSTOMER_ID
Environment=BINTRA_WEBHOOK_SECRET=$CUSTOMER_WEBHOOK_SECRET
# CUSTOMER_BOT_TOKEN is consumed by the workspace-level "snappy-welcome" hook
# (workspace/hooks/snappy-welcome/handler.js), which fires a sub-2s placeholder
# Telegram message on the first inbound per conversation so the customer isn't
# staring at 5–15s of silence during OpenClaw's cold-boot LLM bootstrap.
# OpenClaw itself reads the same token from openclaw.json for the telegram
# channel; this env copy is what the hook's fetch() call uses. Unit file is
# chmod 600; token never leaves this process tree.
Environment=CUSTOMER_BOT_TOKEN=$CUSTOMER_BOT_TOKEN
ExecStartPre=-/bin/bash -c '/usr/local/bin/bintra-report gateway_phase '\''{"phase":"booting"}'\'' || true'
ExecStart=/usr/bin/openclaw gateway
ExecStartPost=-/bin/bash -c '/usr/local/bin/bintra-report gateway_phase '\''{"phase":"ready"}'\'' || true'
ExecStopPost=-/bin/bash -c 'if [ "\$SERVICE_RESULT" != "success" ]; then /usr/local/bin/bintra-report gateway_phase '\''{"phase":"crashed"}'\'' || true; fi'
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
chmod 600 /etc/systemd/system/openclaw.service

echo "==> bintra-research-ping watcher service"
# Long-lived companion that sends a proactive Telegram nudge the moment a
# research file lands on disk. Same EnvironmentFile so CUSTOMER_BOT_TOKEN is
# root-only; never logged. See watchers/research-ping/HOOK.md for rationale.
cat > /etc/systemd/system/bintra-research-ping.service <<EOF
[Unit]
Description=Bintra research-ping watcher for customer $CUSTOMER_ID
After=openclaw.service
Wants=openclaw.service

[Service]
Type=simple
EnvironmentFile=$AUTH_ENV_FILE
Environment=CUSTOMER_ID=$CUSTOMER_ID
Environment=CUSTOMER_BOT_TOKEN=$CUSTOMER_BOT_TOKEN
ExecStart=/usr/bin/node $INSTALL_ROOT/.config-repo/watchers/research-ping/watcher.js
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
chmod 600 /etc/systemd/system/bintra-research-ping.service

echo "==> bintra-credit-watcher service"
# Tails openclaw.service journal for LLM insufficient-credit errors and
# sends the customer a single Telegram alert pointing at their provider
# billing page. See watchers/credit-balance-watcher/HOOK.md for full
# rationale and security notes. Must be executable; install.sh may run
# over a fresh clone where the bit wasn't preserved by the rsync.
chmod +x "$INSTALL_ROOT/.config-repo/watchers/credit-balance-watcher/watcher.sh"
cat > /etc/systemd/system/bintra-credit-watcher.service <<EOF
[Unit]
Description=Bintra credit-balance journal watcher for customer $CUSTOMER_ID
Requires=openclaw.service
After=openclaw.service

[Service]
Type=simple
Environment=CUSTOMER_BOT_TOKEN=$CUSTOMER_BOT_TOKEN
Environment=CUSTOMER_LLM_PROVIDER=$CUSTOMER_LLM_PROVIDER
Environment=CUSTOMER_ID=$CUSTOMER_ID
Environment=BINTRA_WEBHOOK_SECRET=$CUSTOMER_WEBHOOK_SECRET
ExecStart=$INSTALL_ROOT/.config-repo/watchers/credit-balance-watcher/watcher.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
chmod 600 /etc/systemd/system/bintra-credit-watcher.service

echo "==> bintra-heartbeat timer (5-min cadence, HARDENING 1.13)"
# The Manager emits heartbeats once per 24h from the agent loop, but 24h is
# too coarse for outage detection. A systemd timer at 5-min cadence gives the
# panel a "last heartbeat within 2 min / stale / offline" signal regardless of
# customer chat volume, and carries the NRestarts + listener_count telemetry.
cat > /etc/systemd/system/bintra-heartbeat.service <<EOF
[Unit]
Description=Bintra droplet heartbeat reporter
After=openclaw.service

[Service]
Type=oneshot
Environment=CUSTOMER_ID=$CUSTOMER_ID
Environment=BINTRA_WEBHOOK_SECRET=$CUSTOMER_WEBHOOK_SECRET
ExecStart=/usr/local/bin/bintra-report heartbeat
EOF
chmod 600 /etc/systemd/system/bintra-heartbeat.service

cat > /etc/systemd/system/bintra-heartbeat.timer <<EOF
[Unit]
Description=Bintra droplet heartbeat (every 5 min)

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Unit=bintra-heartbeat.service

[Install]
WantedBy=timers.target
EOF
chmod 644 /etc/systemd/system/bintra-heartbeat.timer

systemctl daemon-reload
systemctl enable openclaw.service
systemctl enable bintra-heartbeat.timer
systemctl enable bintra-research-ping.service
systemctl enable bintra-credit-watcher.service
systemctl restart openclaw.service
systemctl restart bintra-heartbeat.timer
systemctl restart bintra-research-ping.service
systemctl restart bintra-credit-watcher.service

echo "==> Health"
sleep 5
if systemctl is-active --quiet openclaw.service; then
  echo "OpenClaw is running."
  exit 0
else
  echo "OpenClaw failed to start. Recent logs:"
  journalctl -u openclaw.service -n 80 --no-pager
  exit 1
fi
