#!/usr/bin/env bash
# Bintra per-customer OpenClaw installer.
# Run on a fresh Ubuntu 24.04 droplet as root (or with sudo).
#
# Required env vars before running:
#   CUSTOMER_ID              — UUID from the Bintra portal users table
#   CUSTOMER_LLM_PROVIDER    — openai | anthropic | gemini
#   CUSTOMER_LLM_MODEL       — e.g. claude-opus-4-6, gpt-5.4, gemini-3.1-pro-preview
#   CUSTOMER_LLM_KEY         — decrypted API key from the portal
#   CUSTOMER_BOT_TOKEN       — Telegram bot token from @BotFather (one bot per customer)
#   CUSTOMER_WEBHOOK_SECRET  — per-customer shared secret the Manager uses to sign
#                              HMAC-SHA256 events it POSTs to the Bintra portal at
#                              /api/droplet/report. Generated by the Bintra provisioner.
#
# Optional:
#   CONFIG_REPO_URL          — git URL for this repo (defaults to https://github.com/bintra/openclaw-config.git)

set -euo pipefail

: "${CUSTOMER_ID:?CUSTOMER_ID not set}"
: "${CUSTOMER_LLM_PROVIDER:?CUSTOMER_LLM_PROVIDER not set}"
: "${CUSTOMER_LLM_MODEL:?CUSTOMER_LLM_MODEL not set}"
: "${CUSTOMER_LLM_KEY:?CUSTOMER_LLM_KEY not set}"
: "${CUSTOMER_BOT_TOKEN:?CUSTOMER_BOT_TOKEN not set}"
: "${CUSTOMER_WEBHOOK_SECRET:?CUSTOMER_WEBHOOK_SECRET not set}"

CONFIG_REPO_URL="${CONFIG_REPO_URL:-https://github.com/redomen2828/bintra-openclaw-config.git}"
INSTALL_ROOT="/opt/bintra"
CONFIG_DIR="$HOME/.openclaw"
SERVICE_FILE="/etc/systemd/system/openclaw.service"

# --- Customer-change state wipe --------------------------------------------
# If the droplet was previously provisioned for a different CUSTOMER_ID,
# the existing workspace/session state belongs to that prior customer. We
# MUST NOT let it bleed into the new customer's environment (MEMORY.md,
# USER.md, IDENTITY.md, memory/ daily logs, knowledge/, sessions). Detect
# and wipe.
#
# Same-customer re-install (config bump, version upgrade) should preserve
# state so conversation history and the Manager's memory stay intact.
#
# Caller can force a wipe with FORCE_WIPE=1 (used by scripts/reset-droplet.ts).
PREV_CUSTOMER_ID=""
if [ -f "$SERVICE_FILE" ]; then
  PREV_CUSTOMER_ID="$(awk -F= '/^Environment=CUSTOMER_ID=/ { print $3; exit }' "$SERVICE_FILE" || true)"
fi

WIPE_STATE=0
WIPE_REASON=""
if [ "${FORCE_WIPE:-0}" = "1" ]; then
  WIPE_STATE=1
  WIPE_REASON="FORCE_WIPE=1"
elif [ -n "$PREV_CUSTOMER_ID" ] && [ "$PREV_CUSTOMER_ID" != "$CUSTOMER_ID" ]; then
  WIPE_STATE=1
  WIPE_REASON="droplet was provisioned for $PREV_CUSTOMER_ID; now reprovisioning for $CUSTOMER_ID"
fi

if [ "$WIPE_STATE" = "1" ]; then
  echo "==> Customer-change state wipe ($WIPE_REASON)"
  systemctl stop openclaw.service 2>/dev/null || true
  rm -f "$INSTALL_ROOT/workspace/MEMORY.md" \
        "$INSTALL_ROOT/workspace/IDENTITY.md" \
        "$INSTALL_ROOT/workspace/USER.md" \
        "$INSTALL_ROOT/workspace/BOOTSTRAP.md" \
        "$INSTALL_ROOT/workspace/HEARTBEAT.md" \
        "$INSTALL_ROOT/workspace/TOOLS.md"
  rm -rf "$INSTALL_ROOT/workspace/memory" \
         "$INSTALL_ROOT/workspace/knowledge" \
         "$INSTALL_ROOT/workspace/state"
  rm -f "$INSTALL_ROOT/sessions/sessions.json"
  rm -rf "$CONFIG_DIR/agents"
  echo "   state wiped"
fi
# --- end wipe ---------------------------------------------------------------

echo "==> System packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git ca-certificates jq

echo "==> Swap (prevents OOM during npm install on 2GB droplets)"
if ! swapon --show | grep -q '/swapfile'; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  if ! grep -q '/swapfile' /etc/fstab; then
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
  fi
fi

echo "==> Node.js 24 LTS"
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
  apt-get install -y nodejs
fi

echo "==> OpenClaw"
npm install -g openclaw@latest

echo "==> Workspace at $INSTALL_ROOT"
mkdir -p "$INSTALL_ROOT" "$INSTALL_ROOT/sessions" "$INSTALL_ROOT/workspace" "/data/research"
if [ ! -d "$INSTALL_ROOT/.config-repo/.git" ]; then
  git clone "$CONFIG_REPO_URL" "$INSTALL_ROOT/.config-repo"
else
  git -C "$INSTALL_ROOT/.config-repo" fetch --all --quiet
  git -C "$INSTALL_ROOT/.config-repo" reset --hard origin/main --quiet
fi
cp -r "$INSTALL_ROOT/.config-repo/workspace/." "$INSTALL_ROOT/workspace/"
# Ensure agent-writable subdirs exist (safe if already present)
mkdir -p "$INSTALL_ROOT/workspace/memory" "$INSTALL_ROOT/workspace/knowledge"
# convothathappened.txt is a dev artifact from the config repo — never ship to customers
rm -f "$INSTALL_ROOT/workspace/convothathappened.txt"
cp "$INSTALL_ROOT/.config-repo/openclaw.json.template" "$INSTALL_ROOT/openclaw.json.template"
cp "$INSTALL_ROOT/.config-repo/research_results.template.json" "$INSTALL_ROOT/research_results.template.json"

echo "==> bintra-report helper (one-command wrapper for /api/droplet/report)"
install -m 0755 "$INSTALL_ROOT/.config-repo/bintra-report.sh" /usr/local/bin/bintra-report

echo "==> Rendering openclaw.json"
mkdir -p "$CONFIG_DIR"

# OpenClaw's model prefix differs from our internal provider enum:
#   portal enum  -> openclaw prefix
#   openai       -> openai
#   anthropic    -> anthropic
#   gemini       -> google
case "$CUSTOMER_LLM_PROVIDER" in
  openai)    OPENCLAW_PREFIX="openai" ;;
  anthropic) OPENCLAW_PREFIX="anthropic" ;;
  gemini)    OPENCLAW_PREFIX="google" ;;
  *) echo "Unknown provider: $CUSTOMER_LLM_PROVIDER" >&2; exit 1 ;;
esac
CUSTOMER_LLM_MODEL_FQN="$OPENCLAW_PREFIX/$CUSTOMER_LLM_MODEL"

sed \
  -e "s|{{CUSTOMER_ID}}|$CUSTOMER_ID|g" \
  -e "s|{{CUSTOMER_BOT_TOKEN}}|$CUSTOMER_BOT_TOKEN|g" \
  -e "s|{{CUSTOMER_LLM_PROVIDER}}|$CUSTOMER_LLM_PROVIDER|g" \
  -e "s|{{CUSTOMER_LLM_MODEL}}|$CUSTOMER_LLM_MODEL|g" \
  -e "s|{{CUSTOMER_LLM_MODEL_FQN}}|$CUSTOMER_LLM_MODEL_FQN|g" \
  "$INSTALL_ROOT/openclaw.json.template" > "$CONFIG_DIR/openclaw.json"

echo "==> Provider API key via auth-profiles.json"
case "$CUSTOMER_LLM_PROVIDER" in
  openai)    ENV_KEY="OPENAI_API_KEY" ;;
  anthropic) ENV_KEY="ANTHROPIC_API_KEY" ;;
  gemini)    ENV_KEY="GOOGLE_API_KEY" ;;
  *) echo "Unknown provider: $CUSTOMER_LLM_PROVIDER" >&2; exit 1 ;;
esac

cat > "$CONFIG_DIR/auth-profiles.json" <<EOF
{
  "env": {
    "$ENV_KEY": "$CUSTOMER_LLM_KEY"
  }
}
EOF
chmod 600 "$CONFIG_DIR/auth-profiles.json"

echo "==> openclaw doctor --fix (auto-migrate + generate gateway token)"
openclaw doctor --fix </dev/null || true

echo "==> systemd service"
cat > /etc/systemd/system/openclaw.service <<EOF
[Unit]
Description=OpenClaw gateway for Bintra customer $CUSTOMER_ID
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=$ENV_KEY=$CUSTOMER_LLM_KEY
Environment=HOME=$HOME
Environment=CUSTOMER_ID=$CUSTOMER_ID
Environment=BINTRA_WEBHOOK_SECRET=$CUSTOMER_WEBHOOK_SECRET
ExecStart=/usr/bin/openclaw gateway
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
chmod 600 /etc/systemd/system/openclaw.service

systemctl daemon-reload
systemctl enable openclaw.service
systemctl restart openclaw.service

echo "==> Health"
sleep 5
if systemctl is-active --quiet openclaw.service; then
  echo "OpenClaw is running."
  exit 0
else
  echo "OpenClaw failed to start. Recent logs:"
  journalctl -u openclaw.service -n 80 --no-pager
  exit 1
fi
